export const DELETE_BOOK = "DELETE_BOOK";
export const EDIT_BOOK = "EDIT_BOOK";
export const ADD_BOOK = "ADD_BOOK";

export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCEEDED = "FETCH_USER_SUCCEEDED";

export const FETCH_USER_POSTS_REQUESTED = "FETCH_USER_POSTS_REQUESTED";
export const FETCH_USER_POSTS_SUCCEEDED = "FETCH_USER_POSTS_SUCCEEDED";
